SELECT O.ID ORDERID, U.USERNAME_, U.NAMESURNAME ,
O.DATE_ ORDERDATE,O.TOTALPRICE ,A.POSTALCODE,A.ADDRESSTEXT,
I.ITEMCODE,I.ITEMNAME,I.BRAND,I.CATEGORY1,I.CATEGORY2,
OD.AMOUNT, OD.UNITPRICE,OD.LINETOTAL,
C.CITY, T.TOWN, D.DISTRICT
FROM ORDERS O 
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID 
JOIN USERS U ON U.ID=O.USERID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN ITEMS I ON I.ID=OD.ITEMID
JOIN CITIES C ON C.ID=A.CITYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
--gerçek veri seti örnek 1
-- 2022 YILI OCAK AYI SÝPARÝÞLERÝ TARÝHE GÖRE SIRALI BÜTÜN SÝPARÝÞLERÝ GETÝR.
--DATE_, ITEMCODE, ITEMNAME , BRAND, CATEGORY1, AMOUNT , UNITPRICE,LINETOTAL KOLONLARININ GETÝRÝLMESÝ GEREKÝYOR.
--BENÝM SORGUM:
SELECT O.DATE_,I.ITEMCODE,I.ITEMNAME,I.BRAND,I.CATEGORY1,
OD.AMOUNT, I.UNITPRICE , OD.LINETOTAL FROM ORDERDETAILS OD 
JOIN ITEMS I ON OD.ITEMID=I.ID
JOIN ORDERS O ON O.ID=OD.ORDERID
GROUP BY DATE_ 
ORDER BY DATE_
--WHERE DATE_  ='2022' AND DATE_='OCAK'

--OLMASI GEREKEN SORGU:
SELECT O.DATE_,I.ITEMCODE,I.ITEMNAME,I.BRAND, I.CATEGORY1,
OD.AMOUNT,OD.UNITPRICE,OD.LINETOTAL
FROM ORDERS O 
JOIN ORDERDETAILS OD ON O.ID=OD.ORDERID
JOIN ITEMS I ON I.ID=OD.ITEMID
WHERE DATE_ BETWEEN '20220101' AND '2022-01-31  23:59:59' --BU KULLANIM DAHA YAYGIN VE DOÐRUDUR.
ORDER BY DATE_ DESC		--BU SORGUDA 31 OCAK TARÝHÝNDEKÝ KAYITLAR GELMEDÝ BUNUN SEBEBÝ:
                        --VERÝ TÝPÝNÝN DATETÝME OLMASIDIR. CONVERT ÝÞLEMÝYLE YA DA SAAT DETAYI VERÝLEREK SORGU DÖNDÜRÜLEBÝLÝR.
--gerçek veri seti örnek 2:Nazmiye Ercan isimli kullanýcýnýn verdiði sipariþlerin detayýný getiren sorgu
--BENÝM SORGUM:
SELECT U.NAMESURNAME, OD.ORDERID, I.ID,I.ITEMCODE, I.ITEMNAME,
I.UNITPRICE,OD.AMOUNT,OD.LINETOTAL FROM USERS U
JOIN ORDERS O ON U.ID=O.USERID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN ITEMS I ON I.ID=OD.ITEMID
WHERE NAMESURNAME ='NAZMÝYE ERCAN'
--ÖRNEK: HER ÞEHRÝN ÝLÇELERÝNÝ GETÝREN SORGUYU YAZINIZ.
SELECT C.CITY ÞEHÝRLER,T.TOWN ÝLÇELER FROM CITIES C
JOIN TOWNS T ON T.CITYID=C.ID
ORDER BY CITY, TOWN
--ÖRNEK: ÝSTANBUL'DA HANGÝ ÝLÇE , NE KADAR MÜÞTERÝ OLDUÐUNU GETÝREN SORGU YAZINIZ.
SELECT C.CITY,T.TOWN, COUNT(U.ID) FROM 
ADDRESS A
JOIN USERS U ON U.ID =A.USERID
JOIN CITIES C ON C.CITY=A.CITYID
JOIN TOWNS T ON T.ID=A.TOWNID
WHERE CITY='ÝSTANBUL'
GROUP BY C.CITY,T.TOWN
--TEKÝL MÜÞTERÝ SAYISINI GETÝRMEK ÝSTÝYORSAK COUNT (DISTINCT) KULLANMALIYIZ. 
--Gerçek veri seti örnek:
--2022 yýlý mart ayýnda 20 ile 30 yaþ arasý müþterilerin verdiði sipariþleri listeleyiniz.
-- yas almak için datediff kullanýlýyor.
SELECT U.NAMESURNAME KULLANICI,DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) YAS,
C.CITY SEHIR ,O.DATE_ TARIH ,O.ID SIPARISID,O.TOTALPRICE TOPLAMTUTAR
FROM USERS U
JOIN ADDRESS A ON A.USERID=U.ID
JOIN CITIES C ON C.ID=A.CITYID
JOIN ORDERS O ON O.ADDRESSID=A.ID
WHERE DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) BETWEEN 20 AND 30 AND 
DATE_ BETWEEN '2022-03-01' AND '2022-03-31 23:59:59'
--ÖRNEK 3 :KULLANICILARIN HANGÝ SEHÝRDE KAÇ ADRESÝ OLDUÐU BÝLGÝSÝNÝ GETÝRÝNÝZ.
SELECT U.ID KULLANICIID,U.NAMESURNAME,C.CITY,COUNT(A.ID) ADRESSAYISI FROM USERS U
JOIN ADDRESS A ON A.USERID=U.ID
JOIN CITIES C ON C.ID=A.CITYID
GROUP BY U.ID ,U.NAMESURNAME,C.CITY
ORDER BY U.NAMESURNAME
--örnek 4: ÝSTANBULDA YILIN ÝLK ÜÇ AYINDA EN ÇOK SATIÞ YAPILAN 10 ÜRÜNÜ GETÝREN SORGUYU YAZINIZ.
SELECT TOP 10
C.CITY SEHIR ,I.ITEMCODE URUNKODU,I.ITEMNAME URUNADI,I.BRAND MARKA,I.CATEGORY1 KAT1,
I.CATEGORY2 KAT2,I.CATEGORY3 KAT3,SUM(OD.AMOUNT) TOPLAMMIKTAR,
SUM(OD.LINETOTAL) TOPLAMTUTAR FROM ORDERS O 
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN ITEMS I ON I.ID=OD.ITEMID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES C ON C.ID=A.CITYID
WHERE CITY='ÝSTANBUL' AND DATE_ BETWEEN '20220101' AND '2022-03-31 23:59:59'
GROUP BY C.CITY,I.ITEMCODE,I.ITEMNAME,I.BRAND,I.CATEGORY1,I.CATEGORY2,I.CATEGORY3,O.TOTALPRICE
ORDER BY SUM(OD.LINETOTAL) DESC
--gerçek veri seti örnek 8 : haftanýn günlerine göre ne kadar alýþveriþ yapýldýðý bilgisini getiren SQL sorgusunu yazýnýz.
SELECT DATENAME(DW,DATE_) GUNADI,	--DATEPART gün numarasýný getirir.DATENAME de gün adýný getirir.
SUM(TOTALPRICE) AS TOPLAMTUTAR, COUNT(ID)
FROM ORDERS
GROUP BY DATEPART(DW,DATE_),DATENAME(DW,DATE_)
ORDER BY DATEPART(DW,DATE_)
--gerçek veri seti örnek 9:saat aralýðýna göre ne kadar alýþveriþ yapýldýðýný getiriniz
SELECT DATEPART(HOUR,DATE_)	SAAT,--DATEPART HOUR ÝLE SAAT ARALIÐINI ÖÐRENEBÝLÝRÝZ 
SUM(TOTALPRICE) TOPLAMTUTAR, COUNT(ID) SIPARISSAYISI
FROM ORDERS
GROUP BY DATEPART(HOUR,DATE_)
ORDER BY 1
--ÖRNEK 10:Her bir sipariþ için sevk etme süresini getiren sorguyu yazýnýz.
SELECT O.ID SIPARISID ,U.NAMESURNAME KULLANICIADI ,
C.CITY SEHIR,O.DATE_ SIPARISTARIHI , I.DATE_ SEVKIYATTARIHI,
DATEDIFF(HOUR,O.DATE_ , I.DATE_) SEVKEDILMESURESI
FROM ORDERS O 
JOIN USERS U ON U.ID=O.USERID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES C ON C.ID=A.CITYID
JOIN INVOICES I ON I.ORDERID=O.ID
ORDER BY O.ID
--ÖRNEK 11:Sipariþlerin genel olarak, bölgelere göre ve þehirlere göre ortalama sevketme sürelerini
--getiren sorguyu yazýnýz.
--1.Genel olarak;
SELECT 
AVG(DATEDIFF(HOUR,O.DATE_ , I.DATE_)) ORT_SEVKEDILMESAATI
FROM ORDERS O 
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES C ON C.ID=A.CITYID
JOIN INVOICES I ON I.ORDERID=O.ID
--2.BÖLGEYE GÖRE;
SELECT C.REGION BOLGE,
AVG(DATEDIFF(HOUR,O.DATE_ , I.DATE_ )* 1.0) ORT_SEVKEDILMESAATI
FROM ORDERS O 
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES C ON C.ID=A.CITYID
JOIN INVOICES I ON I.ORDERID=O.ID
GROUP BY C.REGION
--3.Sehirlere göre,
SELECT C.CITY SEHIR,
AVG(DATEDIFF(HOUR,O.DATE_ , I.DATE_)* 1.0) ORT_SEVKEDILMESAATI
FROM ORDERS O 
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES C ON C.ID=A.CITYID
JOIN INVOICES I ON I.ORDERID=O.ID
GROUP BY C.CITY
--Örnek 12:Sipariþ tarihinin ayý ile fatura tarihinin ayý farklý olan sipariþleri getiriniz.
SELECT O.ID SIPARISNO,O.DATE_ SIPARISTARIHI, I.DATE_ FATURATARIHI, O.TOTALPRICE TOPLAMTUTAR,
DATENAME(MONTH,O.DATE_) SIPARIS_AYI, DATENAME(MONTH,I.DATE_) FATURA_AYI
FROM ORDERS O 
JOIN INVOICES I ON I.ORDERID=O.ID
WHERE DATENAME(MONTH,O.DATE_) <> DATENAME(MONTH,I.DATE_)	--<> bu iþaret farklý anlamýna gelmektedir.
--örnek-13: Her ay için sipariþ tarihinin ayý ile fatura tarihinin ayý farklý olan sipariþ sayýlarýný getiriniz.
SELECT
DATENAME(MONTH,O.DATE_) SIPARIS_AYI,COUNT(DATENAME(MONTH,I.DATE_)) 
FATURASI_SONRAKI_AY_KESILEN_SIPARIS_sAYISI
FROM ORDERS O
JOIN INVOICES I ON I.ORDERID=O.ID
WHERE DATENAME(MONTH,O.DATE_) <> DATENAME(MONTH,I.DATE_)
GROUP BY DATENAME(MONTH,O.DATE_),DATEPART(MONTH,O.DATE_)
ORDER BY DATEPART(MONTH,O.DATE_)
--ÖRNEK-14:Her bir þehirde ne kadar erkek ne kadar kadýn kullanýcý olduðunu getiren sorguyu yazýnýz.
SELECT 
C.CITY SEHIR,U.GENDER CINSIYET,COUNT(U.ID) KULLANICI_SAYISI
FROM USERS U 
JOIN ADDRESS A ON A.USERID=U.ID
JOIN CITIES C ON C.ID=A.CITYID
GROUP BY C.CITY ,U.GENDER
ORDER BY 1
--Örnek 15:Ürün kategorilerini alfabetik olarak ana kategori ve en çok satan alt kategori olacak þekilde getiriniz.
SELECT 
I.CATEGORY1 ANA_KATEGORI,I.CATEGORY2 ALT_KATEGORI,SUM(O.TOTALPRICE) TOPLAMSATIS
FROM ITEMS I
JOIN ORDERDETAILS OD ON OD.ITEMID=I.ID
JOIN ORDERS O ON O.ID=OD.ORDERID
GROUP BY I.CATEGORY1,I.CATEGORY2
ORDER BY 1,3 DESC
--Örnek 16:Deterjan Temizlik ve Gýda kategorilerindeki ürünlerin bölgelere göre yapýlan toplam satýþlarýný
--getiriniz. Items tablosu ,cities tablosu,orderdetails
SELECT 
C.REGION BOLGE,I.CATEGORY1 URUN_KATEGORISI ,SUM(OD.LINETOTAL) TOPLAMSATIS
FROM ORDERDETAILS OD 
JOIN ITEMS I ON I.ID=OD.ITEMID
JOIN ORDERS O ON O.ID=OD.ORDERID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES C ON C.ID=A.CITYID
WHERE I.CATEGORY1='DETERJAN TEMÝZLÝK' AND 'GIDA' --??
GROUP BY C.REGION,I.CATEGORY1
ORDER BY BOLGE

--ÖRNEK 17: Her bir ürün için toplam ne kadar satýþ yapýldýðýný adet ve toplam ciro olarak getiriniz.Ayrýca her bir 
--ürün için en düþük, en yüksek ve ortalama satýþ ve mevcut fiyata göre kar-zarar yapan sorguyu yazýnýz.
--	SQL sorgusunu sanki bir tabloymuþ gibi kullanarak iç içe sorgular yazdýk."Dynamic view"
SELECT 
I.ITEMCODE URUNKODU,I.ITEMNAME URUNADI, I.UNITPRICE BIRIM_FIYAT,
SUM(OD.AMOUNT) TOPLAM_ADET,ROUND(SUM(OD.LINETOTAL),0)TOPLAM_SATIS,
MIN(OD.UNITPRICE) ENDUSUK_FIYAT,MAX(OD.UNITPRICE) ENYUKSEK_FIYAT,
ROUND(AVG(OD.UNITPRICE),2) ORTALAMA_FIYAT, ROUND(SUM(I.UNITPRICE*OD.AMOUNT),0) LISTE_FIYATI_SATIS,
ROUND((SUM(OD.LINETOTAL)-SUM(I.UNITPRICE*OD.AMOUNT)),0) KAR_ZARAR,
ROUND(100*(SUM(OD.LINETOTAL)-SUM(I.UNITPRICE*OD.AMOUNT))
/SUM(I.UNITPRICE*OD.AMOUNT),2) KAR_ZARAR_YUZDE
FROM ORDERDETAILS OD 
JOIN ITEMS I ON I.ID =OD.ITEMID
GROUP BY I.ITEMCODE ,I.ITEMNAME ,I.UNITPRICE
ORDER BY I.ITEMCODE
--ÖRNEK 18: Alýþ liste fiyatý ve satýþ liste fiyatý ile satýlan miktar üzerinden en çok kar elde edilen 10 ürün ile
--en az kar edilen 10 ürünü listeleyiniz.
--En çok kar edilen 10 ürün
SELECT TOP 10 *,
TOPLAM_SATIS-LISTE_FIYATI_SATIS KAR_ZARAR,
ROUND(100*(TOPLAM_SATIS-LISTE_FIYATI_SATIS)/LISTE_FIYATI_SATIS,2) KAR_ZARAR_YUZDE
FROM
(
SELECT 
	I.ITEMCODE URUNKODU,I.ITEMNAME URUNADI, I.UNITPRICE BIRIM_FIYAT,
	SUM(OD.AMOUNT) TOPLAM_ADET,ROUND(SUM(OD.LINETOTAL),0)TOPLAM_SATIS,
	MIN(OD.UNITPRICE) ENDUSUK_FIYAT,MAX(OD.UNITPRICE) ENYUKSEK_FIYAT,
	ROUND(AVG(OD.UNITPRICE),2) ORTALAMA_FIYAT, ROUND(SUM(I.UNITPRICE*OD.AMOUNT),0) LISTE_FIYATI_SATIS
FROM ORDERDETAILS OD 
JOIN ITEMS I ON I.ID =OD.ITEMID
GROUP BY I.ITEMCODE ,I.ITEMNAME ,I.UNITPRICE
)T
ORDER BY KAR_ZARAR_YUZDE DESC
--En az kar edilen 10 ürün
SELECT TOP 10 *,
TOPLAM_SATIS-LISTE_FIYATI_SATIS KAR_ZARAR,
ROUND(100*(TOPLAM_SATIS-LISTE_FIYATI_SATIS)/LISTE_FIYATI_SATIS,2) KAR_ZARAR_YUZDE
FROM
(
SELECT 
	I.ITEMCODE URUNKODU,I.ITEMNAME URUNADI, I.UNITPRICE BIRIM_FIYAT,
	SUM(OD.AMOUNT) TOPLAM_ADET,ROUND(SUM(OD.LINETOTAL),0)TOPLAM_SATIS,
	MIN(OD.UNITPRICE) ENDUSUK_FIYAT,MAX(OD.UNITPRICE) ENYUKSEK_FIYAT,
	ROUND(AVG(OD.UNITPRICE),2) ORTALAMA_FIYAT, ROUND(SUM(I.UNITPRICE*OD.AMOUNT),0) LISTE_FIYATI_SATIS
FROM ORDERDETAILS OD 
JOIN ITEMS I ON I.ID =OD.ITEMID
GROUP BY I.ITEMCODE ,I.ITEMNAME ,I.UNITPRICE
)T
ORDER BY KAR_ZARAR_YUZDE ASC		--Hiçbir þey yazmazsak da en az kar edilenleri döndürür.
--Subquery Konusu
--Her bir kullanýcýnýn sahip olduðu adres sayýsý,geleneksel yöntem
SELECT 
U.ID KULLANICI_ID,U.NAMESURNAME ADSOYAD, COUNT(A.ID) ADRESSAYISI
FROM USERS U ,ADDRESS A
WHERE A.USERID=U.ID
GROUP BY U.ID ,U.NAMESURNAME
ORDER BY 1
--join yöntemi
SELECT 
U.ID KULLANICI_ID,U.NAMESURNAME ADSOYAD, COUNT(A.ID) ADRESSAYISI
FROM USERS U 
JOIN ADDRESS A ON A.USERID=U.ID
GROUP BY U.ID ,U.NAMESURNAME
ORDER BY 1
--subquery yöntemi
SELECT
U.ID KULLANICI_ID,U.NAMESURNAME ADSOYAD,
(SELECT COUNT(*) FROM ADDRESS WHERE USERID=U.ID) ADRESSAYISI
FROM USERS U
--Þehri Ýstanbul olan satýþlarý getirme
SELECT 
O.ID,O.DATE_,O.TOTALPRICE
FROM ORDERS O 
WHERE ADDRESSID IN 
(--Birden fazla alan döndüðünde 'in' i kullanýrýz ama tek alan dönerse '=' de kullanabiliriz.
	SELECT ID FROM ADDRESS	
		WHERE CITYID IN --burada = de kullanýlabilir.
			(SELECT ID FROM CITIES WHERE CITY='Ýstanbul')
)
--örnek1:Her ürün için toplam satýþ adedi, toplam satýþ cirosu,en düþük satýþ fiyatý ve ortalama 
--satýþ fiyatýný getiren sorguyu subquery kullanarak getiriniz.
--Urun analizi:JOIN ile
SELECT I.ITEMCODE URUNKODU,I.ITEMNAME URUNADI,I.BRAND MARKA,
SUM(OD.AMOUNT) TOPLAM_ADET, SUM(OD.LINETOTAL) TOPLAM_CIRO,
MIN(OD.UNITPRICE) ENDUSUK_FIYAT,MAX(OD.UNITPRICE) ENYUKSEK_FIYAT,
ROUND(AVG(OD.UNITPRICE),2) ORTALAMA_FIYAT
FROM ITEMS I 
LEFT JOIN ORDERDETAILS OD ON OD.ITEMID=I.ID
GROUP BY I.ITEMCODE ,I.ITEMNAME ,I.BRAND		--OUTPUT ROWS:1366
--Urun analizi: SUBQUERY ile
SELECT I.ITEMCODE URUNKODU,I.ITEMNAME URUNADI,I.BRAND MARKA,
(SELECT SUM(AMOUNT) FROM ORDERDETAILS WHERE ITEMID=I.ID) TOPLAM_ADET,
(SELECT SUM(LINETOTAL) FROM ORDERDETAILS WHERE ITEMID=I.ID) TOPLAM_CIRO,
(SELECT MIN(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=I.ID) ENDUSUK_FIYAT,
(SELECT MAX(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=I.ID) ENYUKSEK_FIYAT,
(SELECT ROUND(AVG(UNITPRICE),2) FROM ORDERDETAILS WHERE ITEMID=I.ID) ORTALAMA_FIYAT
FROM ITEMS I									--OUTPUT ROWS:1367
--JOIN VE SUBQUERY ARASINDAKI FARKLARI NELERDIR? HANGI DURUMLARDA SUBQUERY HANGI DURUMLARDA JOIN KULLANILMALIDIR?
--Subquery daha okunabilir fakat daha karmaþýk, ilk görüþte join daha avantajlý gibi
--Items tablosunda olan fakat hiçbir satýþý olmayan veriler gelmiyor.
--Join de ürün bilgileri geliyor fakat satýþ bilgileri gelmiyor Bunu önlemek için join yerine left join kullanýlabilir.
--Bir sorgunun performansýna bakarken cpu kullanýmýnýna ya da ne kadar okuma yaptýðýna(*) bakarýz.
--Sorgunun baþýna bu ifade yazýlýnca ne kadar okuma yaptýðýný bulabiliriz.

SET STATISTICS IO ON
SELECT 
I.ITEMCODE URUNKODU,I.ITEMNAME URUNADI,I.BRAND MARKA,
SUM(OD.AMOUNT) TOPLAM_ADET, SUM(OD.LINETOTAL) TOPLAM_CIRO,
MIN(OD.UNITPRICE) ENDUSUK_FIYAT,MAX(OD.UNITPRICE) ENYUKSEK_FIYAT,
ROUND(AVG(OD.UNITPRICE),2) ORTALAMA_FIYAT
FROM ITEMS I 
LEFT JOIN ORDERDETAILS OD ON OD.ITEMID=I.ID
GROUP BY I.ITEMCODE ,I.ITEMNAME ,I.BRAND		
select 1294+445+937=2676 --1 page 8 kb
select 2676*8=21408 --kb lýk okuma gerçekleþtirir join tablosu(örnek üzerinden okuma hesaplama)
--2943 Okuma ;Page SQL server datalarýnýn en küçük yapýtaþý(8KB lýk bloklar)

SET STATISTICS IO ON
SELECT I.ITEMCODE URUNKODU,I.ITEMNAME URUNADI,I.BRAND MARKA,
		(SELECT SUM(AMOUNT) FROM ORDERDETAILS WHERE ITEMID=I.ID) TOPLAM_ADET

FROM ITEMS I
--2805
--Eklenen her bir alt sorgu için okuma nerdeyse %100 artmakta;sorgular teker teker eklenip bu durum test edilebilir.
SET STATISTICS IO ON
SELECT I.ITEMCODE URUNKODU,I.ITEMNAME URUNADI,I.BRAND MARKA,
		(SELECT SUM(AMOUNT) FROM ORDERDETAILS WHERE ITEMID=I.ID) TOPLAM_ADET,
		(SELECT SUM(LINETOTAL) FROM ORDERDETAILS WHERE ITEMID=I.ID) TOPLAM_CIRO,
		(SELECT MIN(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=I.ID) ENDUSUK_FIYAT
FROM ITEMS I 
--Ýki komut daha eklenince okuma 7580 e çýktý.
--SONUÇ:Subquery ler join e göre daha yavaþtýrlar çünkü daha fazla okuma iþlemi gerçekleþtirirler.Sorgularý mümkünse
--join ile yapmalýyýz .En kötü durumda eðer join ile ya da baþka bir þekilde yapamazsak o zaman subquery kullanýlmalý
--20.07.2024
--subquery-join karþýlaþtýrmasý
--joinler boþ verileri vermiyor ancak subquery de boþ olan verileri de yani hepsini görebiliriz.
--ÖRNEK1:Her marka için toplam ürün sayýsý,toplam ana kategori ve alt kategori sayýsýný getiren subquery yi yazýnýz.
SELECT DISTINCT BRAND MARKA,
(SELECT COUNT(DISTINCT CATEGORY1) FROM ITEMS I WHERE BRAND=I.BRAND) ANAKATEGORI_SAYISI,
(SELECT COUNT(DISTINCT CATEGORY2) FROM ITEMS I WHERE BRAND=I.BRAND) ALTKATEGORI_SAYISI,
(SELECT COUNT(ID) FROM ITEMS I WHERE BRAND=I.BRAND) URUN_SAYISI
FROM ITEMS I 
--ÖRNEK2: Gýda ve Deterjan-Temizlik katorilerinin hangi þehirde ne kadar satýldýðýný yanyana getiren sql cümlesini subquery ile yazýnýz.
--gýda ve det tem sütunlarýný yan yana görmek ve ayný zamanda daha az satýrda getirmek için subquery kullandýk.
SELECT
CITY SEHIR,
(		SELECT SUM(OD.LINETOTAL) FROM ORDERS O
		JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
		JOIN ADDRESS A ON A.ID=O.ADDRESSID
		JOIN ITEMS I ON I.ID=OD.ITEMID
		WHERE I.CATEGORY1='GIDA' AND A.CITYID=C.ID
)GIDA ,
(		SELECT SUM(OD.LINETOTAL) FROM ORDERS O
		JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
		JOIN ADDRESS A ON A.ID=O.ADDRESSID
		JOIN ITEMS I ON I.ID=OD.ITEMID
		WHERE I.CATEGORY1='DETERJAN TEMÝZLÝK' AND A.CITYID=C.ID
)  DETERJAN_TEMIZLIK
FROM CITIES C
--Örnek4(Subquery):Her bir þehir için kaç erkek, kaç kadýn	müþteri olduðunu Erkek ve Kadýn sütunlarý yan yana olacak þekilde getiriniz.
SELECT 
CITY SEHIR,
(SELECT COUNT(DISTINCT USERID) FROM USERS U
JOIN ADDRESS A ON A.USERID=U.ID
WHERE U.GENDER='E' AND A.CITYID=C.ID) ERKEKSAYISI,
(SELECT COUNT(DISTINCT USERID) FROM USERS U
JOIN ADDRESS A ON A.USERID=U.ID
WHERE U.GENDER='K' AND A.CITYID=C.ID) KADINSAYISI
FROM CITIES C
--Örnek5:Þehirlerin aylara göre satýþýný aylar yukarýda yan yana sütunlar olacak þekilde getiriniz.
SELECT C.CITY SEHIR,
(SELECT 
ROUND(SUM(O.TOTALPRICE),0)
FROM ORDERS O
JOIN ADDRESS A ON A.ID=O.ADDRESSID
WHERE A.CITYID=C.ID AND DATEPART(MONTH,O.DATE_)=1) OCAK ,
(SELECT 
ROUND(SUM(O.TOTALPRICE),0)
FROM ORDERS O
JOIN ADDRESS A ON A.ID=O.ADDRESSID
WHERE A.CITYID=C.ID AND DATEPART(MONTH,O.DATE_)=2) SUBAT ,
(SELECT 
ROUND(SUM(O.TOTALPRICE),0)
FROM ORDERS O
JOIN ADDRESS A ON A.ID=O.ADDRESSID
WHERE A.CITYID=C.ID AND DATEPART(MONTH,O.DATE_)=3) MART ,
(SELECT 
ROUND(SUM(O.TOTALPRICE),0)
FROM ORDERS O
JOIN ADDRESS A ON A.ID=O.ADDRESSID
WHERE A.CITYID=C.ID AND DATEPART(MONTH,O.DATE_)=4) NISAN ,
(SELECT 
ROUND(SUM(O.TOTALPRICE),0)
FROM ORDERS O
JOIN ADDRESS A ON A.ID=O.ADDRESSID
WHERE A.CITYID=C.ID AND DATEPART(MONTH,O.DATE_)=5) MAYIS ,
(SELECT 
ROUND(SUM(O.TOTALPRICE),0)
FROM ORDERS O
JOIN ADDRESS A ON A.ID=O.ADDRESSID
WHERE A.CITYID=C.ID AND DATEPART(MONTH,O.DATE_)=6) HAZIRAN ,
(SELECT 
ROUND(SUM(O.TOTALPRICE),0)
FROM ORDERS O
JOIN ADDRESS A ON A.ID=O.ADDRESSID
WHERE A.CITYID=C.ID AND DATEPART(MONTH,O.DATE_)=7) TEMMUZ ,
(SELECT 
ROUND(SUM(O.TOTALPRICE),0)
FROM ORDERS O
JOIN ADDRESS A ON A.ID=O.ADDRESSID
WHERE A.CITYID=C.ID AND DATEPART(MONTH,O.DATE_)=8) AGUSTOS ,
(SELECT 
ROUND(SUM(O.TOTALPRICE),0)
FROM ORDERS O
JOIN ADDRESS A ON A.ID=O.ADDRESSID
WHERE A.CITYID=C.ID AND DATEPART(MONTH,O.DATE_)=9) EYLUL ,
(SELECT 
ROUND(SUM(O.TOTALPRICE),0)
FROM ORDERS O
JOIN ADDRESS A ON A.ID=O.ADDRESSID
WHERE A.CITYID=C.ID AND DATEPART(MONTH,O.DATE_)=10) EKIM ,
(SELECT 
ROUND(SUM(O.TOTALPRICE),0)
FROM ORDERS O
JOIN ADDRESS A ON A.ID=O.ADDRESSID
WHERE A.CITYID=C.ID AND DATEPART(MONTH,O.DATE_)=11) KASIM ,
(SELECT 
ROUND(SUM(O.TOTALPRICE),0)
FROM ORDERS O
JOIN ADDRESS A ON A.ID=O.ADDRESSID
WHERE A.CITYID=C.ID AND DATEPART(MONTH,O.DATE_)=12) ARALIK ,
(SELECT 
ROUND(SUM(O.TOTALPRICE),0)
FROM ORDERS O
JOIN ADDRESS A ON A.ID=O.ADDRESSID
WHERE A.CITYID=C.ID) TOPLAM
FROM CITIES C 
ORDER BY CITY
--Örnek6: Bölgelerin aylara göre satýþlarýný aylar yukarýda yan yana sütun olacak þekilde getiriniz.
SELECT BOLGE ,SUM(OCAK) OCAK,SUM(SUBAT) SUBAT,SUM(MART) MART,SUM(NISAN) NISAN,SUM(MAYIS) MAYIS,SUM(HAZIRAN) HAZIRAN,
SUM(TEMMUZ) TEMMUZ,SUM(AGUSTOS) AGUSTOS,SUM(EYLUL) EYLUL,SUM(EKIM) EKIM,SUM(KASIM) KASIM,SUM(ARALIK) ARALIK,SUM(TOPLAM)
TOPLAM

FROM
(SELECT C.REGION BOLGE,C.CITY,
	(SELECT ROUND(SUM(O.TOTALPRICE),0) FROM ORDERS O
	JOIN ADDRESS A ON A.ID=O.ADDRESSID
	WHERE A.CITYID=C.ID AND DATEPART(MONTH,O.DATE_)=1) OCAK ,
	(SELECT ROUND(SUM(O.TOTALPRICE),0) FROM ORDERS O
	JOIN ADDRESS A ON A.ID=O.ADDRESSID
	WHERE A.CITYID=C.ID AND DATEPART(MONTH,O.DATE_)=2) SUBAT ,
	(SELECT ROUND(SUM(O.TOTALPRICE),0) FROM ORDERS O
	JOIN ADDRESS A ON A.ID=O.ADDRESSID
	WHERE A.CITYID=C.ID AND DATEPART(MONTH,O.DATE_)=3) MART ,
	(SELECT ROUND(SUM(O.TOTALPRICE),0) FROM ORDERS O
	JOIN ADDRESS A ON A.ID=O.ADDRESSID
	WHERE A.CITYID=C.ID AND DATEPART(MONTH,O.DATE_)=4) NISAN ,
	(SELECT ROUND(SUM(O.TOTALPRICE),0) FROM ORDERS O
	JOIN ADDRESS A ON A.ID=O.ADDRESSID
	WHERE A.CITYID=C.ID AND DATEPART(MONTH,O.DATE_)=5) MAYIS ,
	(SELECT ROUND(SUM(O.TOTALPRICE),0) FROM ORDERS O
	JOIN ADDRESS A ON A.ID=O.ADDRESSID
	WHERE A.CITYID=C.ID AND DATEPART(MONTH,O.DATE_)=6) HAZIRAN ,
	(SELECT ROUND(SUM(O.TOTALPRICE),0) FROM ORDERS O
	JOIN ADDRESS A ON A.ID=O.ADDRESSID
	WHERE A.CITYID=C.ID AND DATEPART(MONTH,O.DATE_)=7) TEMMUZ ,
	(SELECT ROUND(SUM(O.TOTALPRICE),0) FROM ORDERS O
	JOIN ADDRESS A ON A.ID=O.ADDRESSID
	WHERE A.CITYID=C.ID AND DATEPART(MONTH,O.DATE_)=8) AGUSTOS ,
	(SELECT ROUND(SUM(O.TOTALPRICE),0) FROM ORDERS O
	JOIN ADDRESS A ON A.ID=O.ADDRESSID
	WHERE A.CITYID=C.ID AND DATEPART(MONTH,O.DATE_)=9) EYLUL ,
	(SELECT ROUND(SUM(O.TOTALPRICE),0) FROM ORDERS O
	JOIN ADDRESS A ON A.ID=O.ADDRESSID
	WHERE A.CITYID=C.ID AND DATEPART(MONTH,O.DATE_)=10) EKIM ,
	(SELECT ROUND(SUM(O.TOTALPRICE),0) FROM ORDERS O
	JOIN ADDRESS A ON A.ID=O.ADDRESSID
	WHERE A.CITYID=C.ID AND DATEPART(MONTH,O.DATE_)=11) KASIM ,
	(SELECT ROUND(SUM(O.TOTALPRICE),0) FROM ORDERS O
	JOIN ADDRESS A ON A.ID=O.ADDRESSID
	WHERE A.CITYID=C.ID AND DATEPART(MONTH,O.DATE_)=12) ARALIK ,
	(SELECT ROUND(SUM(O.TOTALPRICE),0) FROM ORDERS O
	JOIN ADDRESS A ON A.ID=O.ADDRESSID
	WHERE A.CITYID=C.ID) TOPLAM

FROM CITIES C )
T
GROUP BY BOLGE
ORDER BY BOLGE
--24.07.2024
--Örnek7(subquery):Her bir þehir için en çok alýþveriþ yapýlan kategori ile en az alýþveriþ yapýlan kategorileri(CATEGORY2) getiren sorguyu yazýnýz
--totalprice,þehir bazýnda categori2 deki en çok ve en az
SELECT C.CITY SEHIR,
(SELECT TOP 1 I.CATEGORY2 FROM ORDERS O
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN ITEMS I ON I.ID=OD.ITEMID
WHERE A.CITYID=C.ID
GROUP BY  I.CATEGORY2
ORDER BY SUM(OD.LINETOTAL) DESC
) EN_FAZLA_SATIS_YAPILAN_KATEGORI,

(SELECT TOP 1 SUM(OD.LINETOTAL) FROM ORDERS O
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN ITEMS I ON I.ID=OD.ITEMID
WHERE A.CITYID=C.ID
GROUP BY  I.CATEGORY2
ORDER BY SUM(OD.LINETOTAL) DESC
) TUTAR,
(SELECT TOP 1 I.CATEGORY2 FROM ORDERS O
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN ITEMS I ON I.ID=OD.ITEMID
WHERE A.CITYID=C.ID
GROUP BY  I.CATEGORY2
ORDER BY SUM(OD.LINETOTAL) ASC
) EN_AZ_SATIS_YAPILAN_KATEGORI,

(SELECT TOP 1 SUM(OD.LINETOTAL) FROM ORDERS O
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN ITEMS I ON I.ID=OD.ITEMID
WHERE A.CITYID=C.ID
GROUP BY  I.CATEGORY2
ORDER BY SUM(OD.LINETOTAL) ASC
) TUTAR

FROM CITIES C 
--örnek8:Her bir þehir için en çok alýþveriþ yapýlan marka ile en az alýþveriþ yapýlan markalarý getiren sorgu.
SELECT C.CITY SEHIR,
(SELECT TOP 1 I.BRAND FROM ORDERS O
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN ITEMS I ON I.ID=OD.ITEMID
WHERE A.CITYID=C.ID
GROUP BY  I.BRAND
ORDER BY I.BRAND DESC) 
EN_FAZLA_SATIS_YAPILAN_MARKA,

(SELECT TOP 1 SUM(OD.LINETOTAL) TOPLAM FROM ORDERS O
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN ITEMS I ON I.ID=OD.ITEMID
WHERE A.CITYID=C.ID
GROUP BY  I.BRAND
ORDER BY SUM(OD.LINETOTAL) DESC) 
TUTAR,
(SELECT TOP 1 I.BRAND FROM ORDERS O
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN ITEMS I ON I.ID=OD.ITEMID
WHERE A.CITYID=C.ID
GROUP BY  I.BRAND
ORDER BY I.BRAND ASC) 
EN_AZ_SATIS_YAPILAN_MARKA,
(SELECT TOP 1 SUM(OD.LINETOTAL) TOPLAM FROM ORDERS O
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN ITEMS I ON I.ID=OD.ITEMID
WHERE A.CITYID=C.ID
GROUP BY  I.BRAND
ORDER BY SUM(OD.LINETOTAL) ASC) 
TUTAR
FROM CITIES C 
--örnek9:Her bir marka için en çok satýlan kategorileri ve en az satýlan kategorileri getiren sorgu
SELECT DISTINCT BRAND,
	(SELECT TOP 1 I.CATEGORY1 FROM ORDERDETAILS OD
	JOIN ITEMS I ON I.ID = OD.ITEMID
	WHERE I.BRAND=I1.BRAND
	GROUP BY I.CATEGORY1 ORDER BY SUM(OD.LINETOTAL) DESC
) EN_FAZLA_SATILAN_KATEGORI,
	(SELECT TOP 1 SUM(OD.LINETOTAL) FROM ORDERDETAILS OD
	JOIN ITEMS I ON I.ID = OD.ITEMID
	WHERE I.BRAND=I1.BRAND
	GROUP BY I.CATEGORY1 ORDER BY SUM(OD.LINETOTAL) DESC
) TUTAR,
	(SELECT TOP 1 I.CATEGORY1 FROM ORDERDETAILS OD
	JOIN ITEMS I ON I.ID = OD.ITEMID
	WHERE I.BRAND=I1.BRAND
	GROUP BY I.CATEGORY1 ORDER BY SUM(OD.LINETOTAL) ASC
) EN_AZ_SATILAN_KATEGORI,
	(SELECT TOP 1 SUM(OD.LINETOTAL) FROM ORDERDETAILS OD
	JOIN ITEMS I ON I.ID = OD.ITEMID
	WHERE I.BRAND=I1.BRAND
	GROUP BY I.CATEGORY1 ORDER BY SUM(OD.LINETOTAL) ASC
) TUTAR
FROM ITEMS I1
--Her bir kategori için	en çok satýlan marka ve en az satýlan markayý yanyana yazdýrýn.
SELECT DISTINCT I1.CATEGORY1 KATEGORI ,
(	SELECT TOP 1 I.BRAND FROM ORDERDETAILS OD
	JOIN ITEMS I ON I.ID=OD.ITEMID
	WHERE I.CATEGORY1=I1.CATEGORY1
	GROUP BY I.BRAND
	ORDER BY SUM(OD.LINETOTAL) DESC
) EN_FAZLA_SATILAN_MARKA,
(	SELECT TOP 1 SUM(OD.LINETOTAL) FROM ORDERDETAILS OD
	JOIN ITEMS I ON I.ID=OD.ITEMID
	WHERE I.CATEGORY1=I1.CATEGORY1
	GROUP BY I.BRAND
	ORDER BY SUM(OD.LINETOTAL) ASC
) TUTAR,
(	SELECT TOP 1 I.BRAND FROM ORDERDETAILS OD
	JOIN ITEMS I ON I.ID=OD.ITEMID
	WHERE I.CATEGORY1=I1.CATEGORY1
	GROUP BY I.BRAND
	ORDER BY SUM(OD.LINETOTAL) ASC
) EN_AZ_SATILAN_MARKA,
(	SELECT TOP 1 SUM(OD.LINETOTAL) FROM ORDERDETAILS OD
	JOIN ITEMS I ON I.ID=OD.ITEMID
	WHERE I.CATEGORY1=I1.CATEGORY1
	GROUP BY I.BRAND
	ORDER BY SUM(OD.LINETOTAL) DESC
) TUTAR
FROM ITEMS I1 
--örnek-11: Ýkiden fazla adresi olan kullanýcýlarý subquery ile getiriniz.Anlamý, subquery yi where þartýnda kullanma
SELECT U.NAMESURNAME KULLANICI,
(SELECT COUNT(*) FROM ADDRESS WHERE USERID=U.ID) ADRES_SAYISI
FROM USERS U
WHERE (SELECT COUNT(*) FROM ADDRESS WHERE USERID=U.ID)>2
--DÝNAMÝC VÝEW YÖNTEMÝ
SELECT * FROM
(	
	SELECT U.NAMESURNAME KULLANICI,
	(SELECT  COUNT(*) FROM ADDRESS WHERE USERID=U.ID) ADRESSAYISI
	FROM USERS U
)T
WHERE ADRESSAYISI>2
--ÖRNEK-12: KULLANICILARDAN AYNI ÞEHÝRDE 2'DEN FAZLA ADRESÝ OLANLARI SUBQUERY ÝLE GETÝRÝNÝZ.
SELECT U.ID, U.NAMESURNAME AD_SOYAD,
(SELECT COUNT(ID) FROM ADDRESS WHERE USERID=U.ID) TOPLAM_ADRES_SAYISI,
(SELECT COUNT(ID) FROM ADDRESS WHERE USERID=U.ID GROUP BY CITYID HAVING COUNT(ID)>2) AYNI_SEHIRDEKI_ADRES_SAYISI
FROM USERS U
WHERE (SELECT COUNT(ID) FROM ADDRESS WHERE USERID=U.ID GROUP BY CITYID HAVING COUNT(ID)>2) IS NOT NULL
--DINAMIC VIEW
SELECT * FROM
(	SELECT U.ID, U.NAMESURNAME AD_SOYAD,
	(SELECT COUNT(ID) FROM ADDRESS WHERE USERID=U.ID) TOPLAM_ADRES_SAYISI,
	(SELECT COUNT(ID) FROM ADDRESS WHERE USERID=U.ID GROUP BY CITYID HAVING COUNT(ID)>2) AYNI_SEHIRDEKI_ADRES_SAYISI
	FROM USERS U
)T WHERE AYNI_SEHIRDEKI_ADRES_SAYISI > 2
--ÖRNEK-12:HER BÝR KULLANICININ EN SON ALIÞVERÝÞ YAPTIÐI TARÝHÝ, SEHRÝ VE ADRESÝ GETÝREN SORGUYU SUBQUERY ÝLE YAZINIZ.
SELECT U.ID, U.NAMESURNAME AD_SOYAD,
(SELECT MAX(DATE_) FROM ORDERS O WHERE USERID=U.ID) EN_SON_ALISVERIS_YAPILAN_TARIH,
(SELECT TOP 1 C.CITY FROM ORDERS O
JOIN ADDRESS A ON A.ID=O.ADDRESSID 
JOIN CITIES C ON C.ID=A.CITYID
WHERE O.USERID=U.ID ORDER BY DATE_ DESC) EN_SON_ALISVERIS_YAPILAN_SEHIR,
(SELECT TOP 1 A.ADDRESSTEXT FROM ORDERS O
JOIN ADDRESS A ON A.ID=O.ADDRESSID JOIN CITIES C ON C.ID=A.CITYID  
WHERE O.USERID=U.ID ORDER BY DATE_ DESC) EN_SON_ALISVERIS_YAPILAN_ADRES,
(	SELECT TOP 1 I.ITEMNAME FROM ORDERS O
	JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	JOIN ITEMS I ON I.ID=OD.ITEMID
	WHERE O.USERID=U.ID 
	ORDER BY DATE_ DESC, OD.ID DESC
) EN_SON_ALINAN_URUN
FROM USERS U
ORDER BY 1
--Cross Apply /03.10.2024
SELECT 
C.CITY SEHIR,D.DATE_ TARIH, 
ISNULL((
	SELECT SUM(O.TOTALPRICE) FROM ORDERS O 
	JOIN ADDRESS A ON A.ID=O.ADDRESSID
	WHERE A.CITYID=C.ID AND CONVERT(DATE,O.DATE_)=D.DATE_
),0) TOPLAMCIRO
FROM CITIES C
CROSS APPLY (SELECT * FROM DATES) D 
WHERE C.CITY='ARTVÝN'
--ÖRNEK-1: HER BÝR SEHÝR ÝÇÝN EN ÇOK ALIÞVERÝÞ YAPILAN MARKA ÝLE EN AZ ALIÞVERÝÞ YAPILAN MARKALARI GETÝREN SORGUYU CROSS APPLY ÝLE YAPINIZ.
SELECT C.CITY SEHIR,ORDERINFO_MAX.BRAND EN_COK_SATILAN_MARKA,ORDERINFO_MAX.TOTALSALE TUTAR,
ORDERINFO_MIN.BRAND EN_AZ_SATILAN_MARKA, ORDERINFO_MIN.TOTALSALE TUTAR 
FROM CITIES C 
CROSS APPLY 
(
	SELECT TOP 1 I.BRAND,SUM(OD.LINETOTAL) TOTALSALE FROM ORDERS O 
	JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	JOIN ADDRESS A ON A.ID=O.ADDRESSID
	JOIN ITEMS I ON I.ID=OD.ITEMID
	WHERE A.CITYID = C.ID
	GROUP BY I.BRAND
	ORDER BY SUM(OD.LINETOTAL) DESC
) ORDERINFO_MAX
CROSS APPLY
(	SELECT TOP 1 I.BRAND, SUM(OD.LINETOTAL) TOTALSALE FROM ORDERS O 
	JOIN ORDERDETAILS OD ON O.ID=OD.ORDERID
	JOIN ADDRESS A ON A.ID=O.ADDRESSID
	JOIN ITEMS I ON I.ID=OD.ITEMID
	WHERE A.CITYID=C.ID
	GROUP BY I.BRAND
	ORDER BY SUM(OD.LINETOTAL) ASC
) ORDERINFO_MIN 
--ÖRNEK-2: HER BÝR KULLANICININ EN SON ALIÞVERÝÞ YAPTIÐI TARÝHÝ, SEHRÝ VE ADRESÝ GETÝREN SORGUYU CROSS APPLY ÝLE YAZINIZ.
SELECT U1.ID , U1.NAMESURNAME ADSOYAD,ORDERINFO.*
FROM USERS U1 
CROSS APPLY 
(SELECT TOP 1 O.DATE_ SON_ALISVERIS_TARIHI,A.ADDRESSTEXT SON_ALISVERIS_ADRESI,
C.CITY SEHIR,T.TOWN ILCE, D.DISTRICT SEMT, I.ITEMNAME URUNADI, O.TOTALPRICE SON_ALISVERIS_TUTARI FROM ORDERS O 
JOIN USERS U ON U.ID=O.USERID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES C ON A.CITYID=C.ID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.DISTRICT=A.DISTRICTID
JOIN ITEMS I ON I.ID=OD.ITEMID
WHERE U.ID=U1.ID
ORDER BY O.DATE_ DESC, OD.ID DESC 
) ORDERINFO
--SELECT INTO 05.10.24
SELECT * INTO KULLANICI_YEDEK FROM USERS
--YEDEKTEN VERÝLERÝ GETÝRMEK ÝÇÝN ÝLK YÖNTEM(KULLANILMASI PEK UYGUN OLMAYAN BÝR YÖNTEMDÝR)
SELECT * INTO USERS FROM KULLANICI_YEDEK--HATA ALINMASININ SEBEBÝ USERS IN OLMASI ,TABLO TRUNCATE EDÝLMELÝ
--ÝKÝNCÝ YÖNTEM
SET IDENTITY_INSERT USERS ON;
INSERT INTO USERS (ID,[USERNAME_],[PASSWORD_],[NAMESURNAME],[EMAIL],[GENDER],[BIRTHDATE],[CREATEDDATE],[TELNR1],[TELNR2])
SELECT ID,[USERNAME_],[PASSWORD_],[NAMESURNAME],[EMAIL],[GENDER],[BIRTHDATE],[CREATEDDATE],[TELNR1],[TELNR2]
FROM KULLANICI_YEDEK
--Select into örnek-2:TABLODAKÝ VERÝLERÝ FÝLTRELEYEREK SÝLDÝÐÝMÝZÝ DÜÞÜNELÝM YEDEKTE OLUP NORMAL TABLODA OLAN VERÝLERÝ NASIL ALABÝLÝRÝZ?
--1.YÖNTEM:
DELETE FROM USERS
WHERE BIRTHDATE BETWEEN '19500101' AND '19601231'
--bu silme iþleminden sonra filtrelenmiþ kayýtlarý da users tablosuna geri almak için;
SELECT * FROM KULLANICI_YEDEK
WHERE ID NOT IN
(SELECT ID FROM USERS)
SET IDENTITY_INSERT USERS ON
INSERT INTO USERS
([ID], [USERNAME_], [PASSWORD_], [NAMESURNAME], [EMAIL], [GENDER], [BIRTHDATE], [CREATEDDATE], [TELNR1], [TELNR2])
SELECT 
[ID], [USERNAME_], [PASSWORD_], [NAMESURNAME], [EMAIL], [GENDER], [BIRTHDATE], [CREATEDDATE], [TELNR1], [TELNR2]
FROM KULLANICI_YEDEK 
WHERE ID NOT IN 
(SELECT ID FROM USERS)
--SELECT INTO ÝLE BOÞ TABLO DOLDURMA(Tablonun script'ini alma)
SELECT * FROM USERS2 --BU ÝÞLEME EÞDEÐER OLARAK TOP 0 YAPILIRSA DA TABLO BOÞ GELÝR YA DA AÞAÐIDAKÝ KODLARDA AYNI ÝÞLEVÝ YERÝNE GETÝRÝR. 
SELECT * FROM WHERE 1=0
SELECT * INTO USERS2 FROM USERS WHERE 1=0
--DATAWAREHOUSE OLUÞTURMA(FLAT TABLE)
SELECT 
O.ID ORDERID, O.STATUS_,O.TOTALPRICE, U.NAMESURNAME,U.ID KULLANICIID, C.CITY,T.TOWN,D.DISTRICT,A.ADDRESSTEXT,A.ID ADRESID,
I.ID ITEMID,I.ITEMNAME,I.BRAND,I.UNITPRICE ITUNITPRICE,OD.ID ORDERDETAÝLID,OD.LINETOTAL, OD.UNITPRICE ODUNITPRICE
INTO SALES
FROM ORDERS O
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN USERS U ON U.ID=O.USERID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES C ON C.ID=A.CITYID
JOIN ITEMS I ON I.ID=OD.ITEMID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
SELECT * FROM SALES
SELECT * FROM USERS WHERE BIRTHDATE='1990-28-01'

